version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
    container_name: api
    expose:
      - '3002'
    ports:
      - '3002:3002'
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  create-task:
    build:
      context: .
      dockerfile: ./docker/CreateTask.Dockerfile
    container_name: createTask
    ports:
      - '3003:3002'
    depends_on:
      - mongodb
      - redis
    links:
      - mongodb
      - redis

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis:6
    restart: always
    ports:
      - 6379:6379